apiVersion: v1
kind: PersistentVolume
metadata:
  name: sathesis-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # If set as "Delete" container would be removed after pvc deletion
  storageClassName: default
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # Important: in the storage account the "Enable network file system v3" should be picked by creation
    volumeHandle: sathesis-rg-thesis-superb-weevil-testblob
    volumeAttributes:
      resourceGroup: rg-thesis-superb-weevil
      storageAccount: sathesisspain
      containerName: testblob
      protocol: nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sathesis-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: sathesis-pv