apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
           wget -O /mnt/blob/bbb_sunflower_2160p_30fps_stereo_abl.mp4.zip https://download.blender.org/demo/movies/BBB/bbb_sunflower_2160p_30fps_stereo_abl.mp4.zip
           for i in $(seq 8 200); do
             cp /mnt/blob/bbb_sunflower_2160p_30fps_stereo_abl.mp4.zip /mnt/blob/bbb_sunflower_2160p_30fps_stereo_abl_$i.mp4.zip
             echo "bbb_sunflower_2160p_30fps_stereo_abl_$i.mp4.zip saved"
           done
        resources:
          #limits:
            #cpu: "1"
            #memory: "4Gi"
        volumeMounts:
        - mountPath: /mnt/blob
          name: blob-storage
      volumes:
      - name: blob-storage
        persistentVolumeClaim:
          claimName: sathesis-pvc