apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/blob/testfile; sleep 5; done"]
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
    volumeMounts:
    - mountPath: /mnt/blob
      name: blob-storage
  volumes:
  - name: blob-storage
    persistentVolumeClaim:
      claimName: sathesis-pvc